apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bloghive
spec:
  selector:
    app: blog-hive
  ports:
    - protocol: TCP
      port: 3000      # <-- CHANGED
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: bloghive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-hive
  template:
    metadata:
      labels:
        app: blog-hive
    spec:
      containers:
        - name: blog-hive
          image: 457795063740.dkr.ecr.us-east-1.amazonaws.com/blog-hive-frontend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://a46b83203b8934d95acfa0263b23040e-140158648.us-east-1.elb.amazonaws.com"